/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_proj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mahe
 */
public class shop2 extends javax.swing.JFrame {
     private String str1;
  private String str2;
   private String p_id;
    /**
    /**
     * Creates new form shop2
     */
    public shop2() {
        initComponents();
    }
 public shop2(String p_id,String str1,String str2){
    this.p_id= p_id;
    this.str1=   str1;
    this.str2= str2;
    initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        w_table = new javax.swing.JTable();
        w_id1 = new javax.swing.JTextField();
        buy = new javax.swing.JButton();
        quantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        w_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "WAREHOUSE ID", "WAREHOUSE ID", "PRODUCT NAME", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(w_table);

        buy.setText("BUY");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        jLabel1.setText("W_ID");

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(w_id1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(buy, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(quantity)))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(buy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
          shop s =new shop(str1,str2);
          s.setVisible(true);
          s.fetch1(); 
    }//GEN-LAST:event_backActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
    String id = w_id1.getText();
    int qty = Integer.parseInt(quantity.getText());
    long amt=0;
    String s="select * from product where p_id='"+p_id+"' and w_id='"+id+"'";
 String s2="update product set w_qty=w_qty-"+qty+" where w_id='"+id+"' and p_id='"+p_id+"'";
 String s1="select * from product where p_id='"+p_id+"' and w_id='"+id+"' and w_qty>="+qty;
 String s3="insert into sold values('"+p_id+"','"+id+"','"+str1+"',sysdate,"+qty+")";

 
 String s6="select price from product where p_id='"+p_id+"' and w_id='"+id+"'";
//step4 execute query  

 try{
      Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step2 create  the connection object  
Connection con1=DriverManager.getConnection(  
"jdbc:oracle:thin:@localhost:1521:orcl","praveen","veerbaba123");  
  
//step3 create the statement object  
Statement stmt1=con1.createStatement(); 
ResultSet rs=stmt1.executeQuery(s);//step4 execute query 
if(rs.next()){
ResultSet rs1=stmt1.executeQuery(s1);//step4 execute query  
 if(rs1.next()){
 ResultSet rs6=stmt1.executeQuery(s6);
             while (rs6.next()) {
                       amt = rs6.getInt("price");   
               }
             
             long total=qty*amt;
            
 String s4="select avl_bal from customer where c_id='"+str1+"'"+" and avl_bal>="+"("+total+")";                
 String s5="update customer set avl_bal=avl_bal-("+total+") where c_id='"+str1+"'";
  ResultSet rs4=stmt1.executeQuery(s4);
 
     if(rs4.next()){
         ResultSet rs3=stmt1.executeQuery(s3);
          ResultSet rs2=stmt1.executeQuery(s2);
          ResultSet rs5=stmt1.executeQuery(s5);
          
          
            if(!(rs2.next())){
    
                      label1.setText("PURCHASED");
                      
 
            }
     }
     else{
         label1.setText("INSUFFICIENT BALANCE");
     }
 }
 else{
     label1.setText("OUT OF STOCK");
 }
}
else{
    label1.setText("INVAID W_ID");
}
//s_details.setModel(DbUtils.resultSetToTableModel(rs2));
      }
      catch(Exception e){
      JOptionPane.showMessageDialog(null, e);
    
      
      }
    }//GEN-LAST:event_buyActionPerformed
    public void  fetch(){

      try{
      Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step2 create  the connection object  
Connection con=DriverManager.getConnection(  
"jdbc:oracle:thin:@localhost:1521:orcl","praveen","veerbaba123");  
  
//step3 create the statement object  
Statement stmt=con.createStatement();  
 String s1=" select w_id,w_name,name,price from product natural join warehouse where p_id='"+p_id+"'";
//step4 execute query  
 
ResultSet rs1=stmt.executeQuery(s1);
//ResultSet rs2=stmt.executeQuery(s2);

w_table.setModel(DbUtils.resultSetToTableModel(rs1));
//s_details.setModel(DbUtils.resultSetToTableModel(rs2));
      }
      catch(Exception e){
      JOptionPane.showMessageDialog(null, e);
    
      
      }
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shop2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton buy;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField w_id1;
    private javax.swing.JTable w_table;
    // End of variables declaration//GEN-END:variables
}
